# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\user\Desktop\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        font = QtGui.QFont("ByteBonce")
        font.setPointSize(30)
        MainWindow.setFont(font)
        icon = QtGui.QIcon("Dice.png")
        icon.addPixmap(QtGui.QPixmap("Dice.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont("ByteBounce")
        font.setPointSize(30)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.bot_claim_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont("ByteBounce")
        font.setPointSize(30)
        self.bot_claim_label.setFont(font)
        self.bot_claim_label.setText("")
        self.bot_claim_label.setObjectName("bot_claim_label")
        self.verticalLayout.addWidget(self.bot_claim_label)
        self.roll_button = QtWidgets.QPushButton(self.centralwidget)
        self.roll_button.setObjectName("roll_button")
        self.verticalLayout.addWidget(self.roll_button)
        self.more_button = QtWidgets.QPushButton(self.centralwidget)
        self.more_button.setObjectName("more_button")
        self.verticalLayout.addWidget(self.more_button)
        self.less_button = QtWidgets.QPushButton(self.centralwidget)
        self.less_button.setObjectName("less_button")
        self.verticalLayout.addWidget(self.less_button)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dice! Dice! Dice!"))
        self.info_label.setText(_translate("MainWindow", "Click \'Roll Dice\' to start!"))
        self.roll_button.setText(_translate("MainWindow", "Roll Dice"))
        self.more_button.setText(_translate("MainWindow", "More"))
        self.less_button.setText(_translate("MainWindow", "Less"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
